import type { Member } from "@taff/schemas";
import { describe, expect, it } from "vitest";
import { type Action, type Actor, can, type Resource } from "./permissions";

const person: Member = {
  id: "owner",
  workspaceId: "workspace",
  userId: "user",
  name: "Person",
  kind: "person",
  role: "member",
};
const agent: Actor = {
  id: "agent",
  workspaceId: "workspace",
  userId: null,
  name: "Agent",
  kind: "agent",
  role: "member",
  scopes: ["tasks:read", "tasks:write"],
};
const task = { workspaceId: "workspace", ownerId: "owner", workerId: "agent" };
describe("permissions", () => {
  it.each<[string, Actor | null, Action, Resource, boolean]>([
    ["anonymous cannot read", null, "workspace:read", task, false],
    ["member can read", person, "workspace:read", task, true],
    [
      "other workspace denied",
      person,
      "workspace:read",
      { workspaceId: "other" },
      false,
    ],
    ["person can create", person, "task:create", task, true],
    ["owner can assign", person, "task:assign", task, true],
    [
      "other member cannot assign",
      person,
      "task:assign",
      { ...task, ownerId: "other" },
      false,
    ],
    [
      "admin can assign",
      { ...person, role: "admin" },
      "task:assign",
      { ...task, ownerId: "other" },
      true,
    ],
    [
      "admin isolated",
      { ...person, role: "admin" },
      "task:assign",
      { ...task, workspaceId: "other" },
      false,
    ],
    [
      "owner moves status",
      person,
      "task:status",
      { ...task, to: "in_progress" },
      true,
    ],
    [
      "worker moves status",
      { ...person, id: "worker" },
      "task:status",
      { ...task, workerId: "worker", to: "needs_review" },
      true,
    ],
    [
      "bystander cannot move status",
      { ...person, id: "other" },
      "task:status",
      { ...task, to: "in_progress" },
      false,
    ],
    [
      "done needs review action",
      person,
      "task:status",
      { ...task, to: "done" },
      false,
    ],
    ["owner reviews", person, "task:review", { ...task, to: "done" }, true],
    ["owner schedules", person, "task:schedule", task, true],
    [
      "admin manages tokens",
      { ...person, role: "admin" },
      "token:manage",
      task,
      true,
    ],
    ["member cannot manage tokens", person, "token:manage", task, false],
    ["own profile allowed", person, "profile:update", { userId: "user" }, true],
    [
      "another profile denied",
      person,
      "profile:update",
      { userId: "other" },
      false,
    ],
    ["agent reads with scope", agent, "workspace:read", task, true],
    [
      "agent without read scope",
      { ...agent, scopes: ["tasks:write"] },
      "workspace:read",
      task,
      false,
    ],
    ["agent creates with write scope", agent, "task:create", task, true],
    [
      "agent without write scope cannot create",
      { ...agent, scopes: ["tasks:read"] },
      "task:create",
      task,
      false,
    ],
    [
      "agent starts its own task",
      agent,
      "task:status",
      { ...task, to: "in_progress" },
      true,
    ],
    [
      "agent cannot start another worker's task",
      agent,
      "task:status",
      { ...task, workerId: "other", to: "in_progress" },
      false,
    ],
    [
      "agent cannot mark done",
      agent,
      "task:status",
      { ...task, to: "done" },
      false,
    ],
    [
      "agent cannot review",
      agent,
      "task:review",
      { ...task, to: "done" },
      false,
    ],
    [
      "agent needs inbox scope to request review",
      agent,
      "task:status",
      { ...task, to: "needs_review" },
      false,
    ],
    [
      "agent creates unassigned or self-assigned work",
      agent,
      "task:create",
      { workspaceId: "workspace", toWorkerId: "agent" },
      true,
    ],
    [
      "agent cannot create work for someone else",
      agent,
      "task:create",
      { workspaceId: "workspace", toWorkerId: "owner" },
      false,
    ],
    [
      "agent releases its task",
      agent,
      "task:assign",
      { ...task, toWorkerId: null },
      true,
    ],
    [
      "agent takes an unassigned task",
      agent,
      "task:assign",
      { ...task, workerId: null, toWorkerId: "agent" },
      true,
    ],
    [
      "agent cannot hand its task to a person",
      agent,
      "task:assign",
      { ...task, toWorkerId: "owner" },
      false,
    ],
    [
      "agent cannot take another worker's task",
      agent,
      "task:assign",
      { ...task, workerId: "other", toWorkerId: "agent" },
      false,
    ],
    [
      "agent requests review with scope",
      { ...agent, scopes: ["tasks:write", "inbox:review"] },
      "task:status",
      { ...task, to: "needs_review" },
      true,
    ],
    [
      "agent schedules its task with scope",
      { ...agent, scopes: ["calendar:write"] },
      "task:schedule",
      task,
      true,
    ],
    [
      "agent cannot schedule without scope",
      agent,
      "task:schedule",
      task,
      false,
    ],
    [
      "agent never manages tokens",
      {
        ...agent,
        role: "admin",
        scopes: ["tasks:read", "tasks:write", "calendar:write", "inbox:review"],
      },
      "token:manage",
      task,
      false,
    ],
    [
      "agent cannot change person profile",
      agent,
      "profile:update",
      { userId: "user" },
      false,
    ],
    [
      "agent isolated to its workspace",
      agent,
      "workspace:read",
      { workspaceId: "other" },
      false,
    ],
  ])("%s", (_, actor, action, resource, allowed) =>
    expect(can(actor, action, resource)).toBe(allowed),
  );
});

describe("M3 permission decisions", () => {
  const scoped = {
    ...agent,
    scopes: [
      "tasks:read",
      "tasks:write",
      "inbox:review",
      "files:write",
    ] as Actor["scopes"],
  };
  const resource = {
    ...task,
    taskId: "task",
    runId: "run",
    agentId: "agent",
    capability: "repo.read" as const,
  };
  const validGrant = {
    capability: "repo.read" as const,
    taskId: "task",
    runId: "run",
    status: "allowed" as const,
    expiresAt: new Date(Date.now() + 60000).toISOString(),
  };
  it.each<[string, Actor | null, Action, Resource, boolean]>([
    [
      "request review requires inbox scope",
      agent,
      "run:request_review",
      resource,
      false,
    ],
    ["request review with scope", scoped, "run:request_review", resource, true],
    [
      "calendar-only token requests matching grant",
      { ...scoped, scopes: ["calendar:write"] },
      "grant:request",
      { ...resource, capability: "calendar.schedule" },
      true,
    ],
    [
      "file-only token requests matching grant",
      { ...scoped, scopes: ["files:write"] },
      "grant:request",
      { ...resource, capability: "files.attach" },
      true,
    ],
    [
      "allow capability",
      {
        ...scoped,
        permissions: [{ capability: "repo.read", decision: "allow" }],
      },
      "capability:use",
      resource,
      true,
    ],
    ["ask without grant", scoped, "capability:use", resource, false],
    [
      "ask with scoped future grant",
      { ...scoped, grants: [validGrant] },
      "capability:use",
      resource,
      true,
    ],
    [
      "expired grant denied",
      {
        ...scoped,
        grants: [{ ...validGrant, expiresAt: new Date(0).toISOString() }],
      },
      "capability:use",
      resource,
      false,
    ],
    [
      "pending grant denied",
      { ...scoped, grants: [{ ...validGrant, status: "pending" }] },
      "capability:use",
      resource,
      false,
    ],
    [
      "denied grant denied",
      { ...scoped, grants: [{ ...validGrant, status: "denied" }] },
      "capability:use",
      resource,
      false,
    ],
    [
      "revoked grant denied",
      { ...scoped, grants: [{ ...validGrant, status: "revoked" }] },
      "capability:use",
      resource,
      false,
    ],
    [
      "other task grant denied",
      { ...scoped, grants: [{ ...validGrant, taskId: "other" }] },
      "capability:use",
      resource,
      false,
    ],
    [
      "other run grant denied",
      { ...scoped, grants: [{ ...validGrant, runId: "other" }] },
      "capability:use",
      resource,
      false,
    ],
    [
      "workspace-wide grant",
      { ...scoped, grants: [{ ...validGrant, taskId: null, runId: null }] },
      "capability:use",
      resource,
      true,
    ],
    [
      "deny beats grant",
      {
        ...scoped,
        permissions: [{ capability: "repo.read", decision: "deny" }],
        grants: [validGrant],
      },
      "capability:use",
      resource,
      false,
    ],
    [
      "grant cannot extend token",
      { ...scoped, scopes: ["tasks:read"], grants: [validGrant] },
      "capability:use",
      resource,
      false,
    ],
    ["missing file scope", agent, "files:attach", resource, false],
    [
      "file scope allows assigned agent",
      scoped,
      "files:attach",
      resource,
      true,
    ],
    [
      "file deny beats token",
      {
        ...scoped,
        permissions: [{ capability: "files.attach", decision: "deny" }],
      },
      "files:attach",
      resource,
      false,
    ],
    [
      "task deny reaches existing create",
      {
        ...scoped,
        permissions: [{ capability: "tasks.write", decision: "deny" }],
      },
      "task:create",
      resource,
      false,
    ],
    ["agent own run", scoped, "run:start", resource, true],
    [
      "other worker run denied",
      scoped,
      "run:start",
      { ...resource, workerId: "other" },
      false,
    ],
    ["owner controls run", person, "run:control", resource, true],
    [
      "member cannot control run",
      { ...person, id: "other" },
      "run:control",
      resource,
      false,
    ],
    ["assigned agent controls run", scoped, "run:control", resource, true],
    ["assigned agent submits run", scoped, "run:submit", resource, true],
    [
      "other agent cannot submit",
      { ...scoped, id: "other" },
      "run:submit",
      resource,
      false,
    ],
    [
      "default always review",
      scoped,
      "task:finish",
      { ...resource, requestedReview: false },
      false,
    ],
    [
      "always review cannot be bypassed",
      { ...scoped, reviewPolicy: "always_review" },
      "task:finish",
      { ...resource, requestedReview: false },
      false,
    ],
    [
      "ask only may complete",
      { ...scoped, reviewPolicy: "ask_only" },
      "task:finish",
      { ...resource, requestedReview: false },
      true,
    ],
    [
      "ask only respects explicit review",
      { ...scoped, reviewPolicy: "ask_only" },
      "task:finish",
      { ...resource, requestedReview: true },
      false,
    ],
    ["only admin changes policy", person, "agent:manage", resource, false],
    [
      "admin changes policy",
      { ...person, role: "admin" },
      "agent:manage",
      resource,
      true,
    ],
    [
      "agent admin cannot change policy",
      { ...scoped, role: "admin" },
      "agent:manage",
      resource,
      false,
    ],
    ["own agent requests grant", scoped, "grant:request", resource, true],
    [
      "other agent cannot request grant",
      { ...scoped, id: "other" },
      "grant:request",
      resource,
      false,
    ],
    [
      "grant request needs scope",
      { ...scoped, scopes: ["tasks:read"] },
      "grant:request",
      resource,
      false,
    ],
    ["task owner requests grant", person, "grant:request", resource, true],
    [
      "supervisor decides grant",
      person,
      "grant:decide",
      { ...resource, supervisorId: "owner" },
      true,
    ],
    ["non-supervisor denied", person, "grant:decide", resource, false],
    [
      "admin decides grant",
      { ...person, role: "admin" },
      "grant:decide",
      resource,
      true,
    ],
    [
      "agent never decides",
      scoped,
      "grant:decide",
      { ...resource, supervisorId: "agent" },
      false,
    ],
    [
      "supervisor reviews",
      { ...person, id: "supervisor" },
      "task:review",
      { ...resource, supervisorId: "supervisor" },
      true,
    ],
    [
      "agent cannot review even supervisor",
      scoped,
      "task:review",
      { ...resource, supervisorId: "agent" },
      false,
    ],
    [
      "member comments",
      { ...person, id: "other" },
      "review:comment",
      resource,
      true,
    ],
    ["assigned agent comments", scoped, "review:comment", resource, true],
    [
      "other agent cannot comment",
      { ...scoped, id: "other" },
      "review:comment",
      resource,
      false,
    ],
    ["human inbox", person, "inbox:read", resource, true],
    ["agent inbox denied", scoped, "inbox:read", resource, false],
    [
      "own inbox state",
      person,
      "inbox:update",
      { ...resource, memberId: "owner" },
      true,
    ],
    [
      "other inbox state denied",
      person,
      "inbox:update",
      { ...resource, memberId: "other" },
      false,
    ],
    [
      "admin cannot read another inbox",
      { ...person, role: "admin" },
      "inbox:update",
      { ...resource, memberId: "other" },
      false,
    ],
    [
      "cross workspace deny new run",
      scoped,
      "run:start",
      { ...resource, workspaceId: "other" },
      false,
    ],
  ])("%s", (_, actor, action, target, expected) =>
    expect(can(actor, action, target)).toBe(expected),
  );
});

describe("M5 permission decisions", () => {
  it.each<[string, Actor, Action, Resource, boolean]>([
    [
      "admin manages organization",
      { ...person, role: "admin" },
      "workspace:manage",
      task,
      true,
    ],
    [
      "member cannot manage organization",
      person,
      "workspace:manage",
      task,
      false,
    ],
    [
      "guest cannot add workspace agents",
      { ...person, role: "guest" },
      "workspace:manage",
      task,
      false,
    ],
    [
      "agent admin cannot manage organization",
      { ...agent, role: "admin" },
      "workspace:manage",
      task,
      false,
    ],
    [
      "admin manages projects",
      { ...person, role: "admin" },
      "project:manage",
      task,
      true,
    ],
    ["member cannot manage projects", person, "project:manage", task, false],
    ["owner edits", person, "task:edit", task, true],
    [
      "bystander cannot edit",
      { ...person, id: "other" },
      "task:edit",
      task,
      false,
    ],
    ["assigned scoped agent edits", agent, "task:edit", task, true],
    [
      "agent cannot edit other worker",
      agent,
      "task:edit",
      { ...task, workerId: "other" },
      false,
    ],
    [
      "scope cannot be widened",
      { ...agent, scopes: ["tasks:read"] },
      "task:edit",
      task,
      false,
    ],
    [
      "deny beats write scope",
      {
        ...agent,
        permissions: [{ capability: "tasks.write", decision: "deny" }],
      },
      "task:edit",
      task,
      false,
    ],
    ["owner changes owner", person, "task:owner", task, true],
    ["agent never changes owner", agent, "task:owner", task, false],
    ["member comments", { ...person, id: "other" }, "task:comment", task, true],
    ["assigned agent comments", agent, "task:comment", task, true],
    [
      "other agent cannot comment",
      { ...agent, id: "other" },
      "task:comment",
      task,
      false,
    ],
    [
      "guest can read",
      { ...person, role: "guest" },
      "workspace:read",
      task,
      true,
    ],
    [
      "guest can read own inbox",
      { ...person, role: "guest" },
      "inbox:read",
      task,
      true,
    ],
    [
      "guest cannot edit",
      { ...person, role: "guest" },
      "task:edit",
      task,
      false,
    ],
    [
      "guest cannot comment",
      { ...person, role: "guest" },
      "task:comment",
      task,
      false,
    ],
    [
      "guest cannot review as owner",
      { ...person, role: "guest" },
      "task:review",
      task,
      false,
    ],
    [
      "guest cannot create",
      { ...person, role: "guest" },
      "task:create",
      task,
      false,
    ],
    [
      "guest cannot use generic capability",
      { ...person, role: "guest" },
      "capability:use",
      { ...task, capability: "tasks.write" },
      false,
    ],
    [
      "cross-workspace edit denied",
      person,
      "task:edit",
      { ...task, workspaceId: "other" },
      false,
    ],
    [
      "cross-workspace admin denied",
      { ...person, role: "admin" },
      "workspace:manage",
      { workspaceId: "other" },
      false,
    ],
  ])("%s", (_, actor, action, resource, expected) =>
    expect(can(actor, action, resource)).toBe(expected),
  );
});

describe("M5 authenticated workspace identity rules", () => {
  for (const action of ["workspace:create", "workspace:join"] as const) {
    it.each<[string, Actor | null, Resource, boolean]>([
      ["person acts for self", person, { userId: "user" }, true],
      [
        "guest can create or accept new workspace",
        { ...person, role: "guest" },
        { userId: "user" },
        true,
      ],
      [
        "another user cannot be impersonated",
        person,
        { userId: "other" },
        false,
      ],
      ["anonymous denied", null, { userId: "user" }, false],
      ["agent denied", agent, { userId: "user" }, false],
      ["workspace resource is not user identity", person, task, false],
    ])(`${action}: %s`, (_, actor, resource, expected) =>
      expect(can(actor, action, resource)).toBe(expected),
    );
  }
});
