import type { Member } from "@taff/schemas";
import { describe, expect, it } from "vitest";
import { type Action, type Actor, can, type Resource } from "./permissions";

const person: Member = {
  id: "owner",
  workspaceId: "workspace",
  userId: "user",
  name: "Person",
  kind: "person",
  role: "member",
};
const agent: Actor = {
  id: "agent",
  workspaceId: "workspace",
  userId: null,
  name: "Agent",
  kind: "agent",
  role: "member",
  scopes: ["tasks:read", "tasks:write"],
};
const task = { workspaceId: "workspace", ownerId: "owner", workerId: "agent" };
describe("permissions", () => {
  it.each<[string, Actor | null, Action, Resource, boolean]>([
    ["anonymous cannot read", null, "workspace:read", task, false],
    ["member can read", person, "workspace:read", task, true],
    [
      "other workspace denied",
      person,
      "workspace:read",
      { workspaceId: "other" },
      false,
    ],
    ["person can create", person, "task:create", task, true],
    ["owner can assign", person, "task:assign", task, true],
    [
      "other member cannot assign",
      person,
      "task:assign",
      { ...task, ownerId: "other" },
      false,
    ],
    [
      "admin can assign",
      { ...person, role: "admin" },
      "task:assign",
      { ...task, ownerId: "other" },
      true,
    ],
    [
      "admin isolated",
      { ...person, role: "admin" },
      "task:assign",
      { ...task, workspaceId: "other" },
      false,
    ],
    [
      "owner moves status",
      person,
      "task:status",
      { ...task, to: "in_progress" },
      true,
    ],
    [
      "worker moves status",
      { ...person, id: "worker" },
      "task:status",
      { ...task, workerId: "worker", to: "needs_review" },
      true,
    ],
    [
      "bystander cannot move status",
      { ...person, id: "other" },
      "task:status",
      { ...task, to: "in_progress" },
      false,
    ],
    [
      "done needs review action",
      person,
      "task:status",
      { ...task, to: "done" },
      false,
    ],
    ["owner reviews", person, "task:review", { ...task, to: "done" }, true],
    ["owner schedules", person, "task:schedule", task, true],
    [
      "admin manages tokens",
      { ...person, role: "admin" },
      "token:manage",
      task,
      true,
    ],
    ["member cannot manage tokens", person, "token:manage", task, false],
    ["own profile allowed", person, "profile:update", { userId: "user" }, true],
    [
      "another profile denied",
      person,
      "profile:update",
      { userId: "other" },
      false,
    ],
    ["agent reads with scope", agent, "workspace:read", task, true],
    [
      "agent without read scope",
      { ...agent, scopes: ["tasks:write"] },
      "workspace:read",
      task,
      false,
    ],
    ["agent creates with write scope", agent, "task:create", task, true],
    [
      "agent without write scope cannot create",
      { ...agent, scopes: ["tasks:read"] },
      "task:create",
      task,
      false,
    ],
    [
      "agent starts its own task",
      agent,
      "task:status",
      { ...task, to: "in_progress" },
      true,
    ],
    [
      "agent cannot start another worker's task",
      agent,
      "task:status",
      { ...task, workerId: "other", to: "in_progress" },
      false,
    ],
    [
      "agent cannot mark done",
      agent,
      "task:status",
      { ...task, to: "done" },
      false,
    ],
    [
      "agent cannot review",
      agent,
      "task:review",
      { ...task, to: "done" },
      false,
    ],
    [
      "agent needs inbox scope to request review",
      agent,
      "task:status",
      { ...task, to: "needs_review" },
      false,
    ],
    [
      "agent releases its task",
      agent,
      "task:assign",
      { ...task, toWorkerId: null },
      true,
    ],
    [
      "agent takes an unassigned task",
      agent,
      "task:assign",
      { ...task, workerId: null, toWorkerId: "agent" },
      true,
    ],
    [
      "agent cannot hand its task to a person",
      agent,
      "task:assign",
      { ...task, toWorkerId: "owner" },
      false,
    ],
    [
      "agent cannot take another worker's task",
      agent,
      "task:assign",
      { ...task, workerId: "other", toWorkerId: "agent" },
      false,
    ],
    [
      "agent requests review with scope",
      { ...agent, scopes: ["inbox:review"] },
      "task:status",
      { ...task, to: "needs_review" },
      true,
    ],
    [
      "agent schedules its task with scope",
      { ...agent, scopes: ["calendar:write"] },
      "task:schedule",
      task,
      true,
    ],
    [
      "agent cannot schedule without scope",
      agent,
      "task:schedule",
      task,
      false,
    ],
    [
      "agent never manages tokens",
      {
        ...agent,
        role: "admin",
        scopes: ["tasks:read", "tasks:write", "calendar:write", "inbox:review"],
      },
      "token:manage",
      task,
      false,
    ],
    [
      "agent cannot change person profile",
      agent,
      "profile:update",
      { userId: "user" },
      false,
    ],
    [
      "agent isolated to its workspace",
      agent,
      "workspace:read",
      { workspaceId: "other" },
      false,
    ],
  ])("%s", (_, actor, action, resource, allowed) =>
    expect(can(actor, action, resource)).toBe(allowed),
  );
});
